from __future__ import annotations

import argparse
import json
from pathlib import Path
from typing import Any


def _load_json(path: Path | str) -> dict[str, Any]:
    return json.loads(Path(path).read_text(encoding="utf-8"))


def _tex_escape(value: Any) -> str:
    text = str(value)
    replacements = {
        "\\": r"\textbackslash{}",
        "&": r"\&",
        "%": r"\%",
        "$": r"\$",
        "#": r"\#",
        "_": r"\_",
        "{": r"\{",
        "}": r"\}",
        "~": r"\textasciitilde{}",
        "^": r"\textasciicircum{}",
    }
    return "".join(replacements.get(ch, ch) for ch in text)


def _pct(value: float | int | None, digits: int = 1) -> str:
    if value is None:
        return "--"
    return f"{float(value) * 100:.{digits}f}\\%"


def _num(value: float | int | None, digits: int = 4) -> str:
    if value is None:
        return "--"
    return f"{float(value):.{digits}f}"


def _int(value: float | int | None) -> str:
    if value is None:
        return "--"
    return str(int(value))


def _write(path: Path, content: str) -> None:
    path.write_text(content.rstrip() + "\n", encoding="utf-8")


def _macro_name(raw: str) -> str:
    return "".join(part.capitalize() for part in raw.replace("-", "_").split("_"))


def _display_label(raw: str) -> str:
    return raw.replace("_", " ")


def _write_numbers(
    *,
    headline: dict[str, Any],
    suite: dict[str, Any],
    human: dict[str, Any],
    output_dir: Path,
) -> None:
    metrics = headline["headline_metrics"]
    progress_failed = suite.get("failed_run_ids", [])
    macros: dict[str, str] = {
        "SMURunId": _tex_escape(headline["run_id"]),
        "SMUEpisodes": str(headline["episode_count"]),
        "SMUSteps": str(headline["step_count"]),
        "SMUTickerCount": str(len(headline["tickers"])),
        "SMUCompletedRuns": str(suite["completed_run_count"]),
        "SMUPlannedRuns": str(suite["planned_run_count"]),
        "SMUMissingRuns": str(len(suite.get("missing_run_ids", []))),
        "SMUFailedRuns": str(len(progress_failed)),
        "SMUHumanAuditExpected": str(human["completion"]["expected_count"]),
        "SMUHumanAuditComplete": str(human["completion"]["expected_count"] - human["completion"]["adjudicated_missing_count"]),
        "SMUSelectiveRisk": _pct(metrics["selective_risk"], 2),
        "SMUAlwaysActRisk": _pct(metrics["always_act_risk"], 2),
        "SMUAbstentionGain": _num(metrics["abstention_gain"], 4),
        "SMUReviewRate": _pct(metrics["review_rate"], 2),
        "SMUInterventionRate": _pct(metrics["intervention_rate"], 2),
        "SMUMajorityECE": _num(metrics["majority_expected_calibration_error"], 4),
        "SMUExecutedECE": _num(metrics["executed_expected_calibration_error"], 4),
        "SMUExecutedCoverage": _pct(metrics["executed_coverage"], 2),
        "SMUBudgetLimitedApprovals": str(metrics["budget_limited_low_reliability_approvals"]),
    }
    lines = [
        "% Auto-generated by scripts/export_submission_latex_assets.py; do not edit by hand.",
    ]
    for name, value in macros.items():
        lines.append(rf"\newcommand{{\{name}}}{{{value}}}")
    _write(output_dir / "submission_numbers.tex", "\n".join(lines))


def _headline_table(headline: dict[str, Any], output_dir: Path) -> None:
    metrics = headline["headline_metrics"]
    rows = [
        ("Episodes / steps", f"{headline['episode_count']} / {headline['step_count']}"),
        ("Executed coverage", _pct(metrics["executed_coverage"], 2)),
        ("Selective risk", _pct(metrics["selective_risk"], 2)),
        ("Always-act majority risk", _pct(metrics["always_act_risk"], 2)),
        ("Abstention gain", _num(metrics["abstention_gain"], 4)),
        ("Majority-vote ECE", _num(metrics["majority_expected_calibration_error"], 4)),
        ("Executed-action ECE", _num(metrics["executed_expected_calibration_error"], 4)),
        ("Review rate", _pct(metrics["review_rate"], 2)),
        ("Intervention rate", _pct(metrics["intervention_rate"], 2)),
        ("Budget-limited low-reliability approvals", _int(metrics["budget_limited_low_reliability_approvals"])),
        ("Policy violation rate", _pct(metrics["policy_violation_rate"], 2)),
    ]
    body = "\n".join(rf"{_tex_escape(name)} & {value} \\" for name, value in rows)
    _write(
        output_dir / "headline_metrics_table.tex",
        rf"""
\begin{{table}}[H]
\centering
\caption{{Canonical headline-run safety metrics. Values come directly from \texttt{{outputs/benchmark/smu\_headline\_v1/summary.json}}.}}
\label{{tab:headline-metrics}}
\begin{{tabular}}{{lr}}
\toprule
Metric & Value \\
\midrule
{body}
\bottomrule
\end{{tabular}}
\end{{table}}
""",
    )


def _corruption_table(headline: dict[str, Any], output_dir: Path) -> None:
    body = "\n".join(
        rf"{_tex_escape(row['slice'].title())} & {_int(row['steps'])} & {_pct(row['majority_error_rate'])} & {_pct(row['executed_error_rate'])} & {_pct(row['review_rate'])} & {_num(row['average_reward'], 4)} \\"
        for row in headline["corruption_comparison"]
    )
    _write(
        output_dir / "corruption_table.tex",
        rf"""
\begin{{table}}[H]
\centering
\caption{{Corruption-conditioned performance in the headline run. Corrupted evidence increases review routing sharply, but executed correctness still degrades.}}
\label{{tab:corruption}}
\scriptsize
\resizebox{{\columnwidth}}{{!}}{{%
\begin{{tabular}}{{lrrrrr}}
\toprule
Slice & Steps & Majority error & Executed error & Review rate & Reward/step \\
\midrule
{body}
\bottomrule
\end{{tabular}}
}}
\end{{table}}
""",
    )


def _regime_table(headline: dict[str, Any], output_dir: Path) -> None:
    rows = sorted(headline["regime_table"], key=lambda row: row["majority_error_rate"], reverse=True)
    body = "\n".join(
        rf"{_tex_escape(_display_label(row['regime_label']))} & {_int(row['steps'])} & {_pct(row['majority_error_rate'])} & {_pct(row['executed_error_rate'])} & {_pct(row['review_rate'])} & {_num(row['average_reward'], 4)} \\"
        for row in rows
    )
    _write(
        output_dir / "regime_table.tex",
        rf"""
\begin{{table}}[H]
\centering
\caption{{Regime-stratified diagnostics, sorted by majority error. The residual bucket stays visible rather than hidden.}}
\label{{tab:regime}}
\scriptsize
\resizebox{{\columnwidth}}{{!}}{{%
\begin{{tabular}}{{lrrrrr}}
\toprule
Regime & Steps & Majority error & Executed error & Review rate & Reward/step \\
\midrule
{body}
\bottomrule
\end{{tabular}}
}}
\end{{table}}
""",
    )


def _suite_table(preliminary: dict[str, Any], output_dir: Path) -> None:
    rows = preliminary["suite"]["condition_table"]
    body = "\n".join(
        rf"{_tex_escape(row['condition'])} & {_int(row['n'])} & {_pct(row['selective_risk'])} & {_pct(row['review_rate'])} & {_pct(row['intervention_rate'])} & {_num(row['reward_per_step'], 4)} & {_num(row['executed_expected_calibration_error'], 4)} \\"
        for row in rows
    )
    _write(
        output_dir / "suite_condition_table.tex",
        rf"""
\begin{{table}}[H]
\centering
\caption{{Completed publication-suite conditions. The table uses only validated completed \texttt{{gpt-5.4-mini}} cells and excludes the quota-interrupted \texttt{{gpt-5.4}} run.}}
\label{{tab:suite-conditions}}
\scriptsize
\resizebox{{\columnwidth}}{{!}}{{%
\begin{{tabular}}{{lrrrrrr}}
\toprule
Condition & $n$ & Selective risk & Review rate & Intervention rate & Reward/step & Executed ECE \\
\midrule
{body}
\bottomrule
\end{{tabular}}
}}
\end{{table}}
""",
    )


def _matrix_table(headline: dict[str, Any], output_dir: Path) -> None:
    rows = [row for row in headline["experimental_matrix"] if row["coverage"] is not None]
    body = "\n".join(
        rf"{_tex_escape(row['label'])} & {_pct(row['coverage'])} & {_pct(row['error_rate'])} & {_num(row['average_reward'], 4)} \\"
        for row in rows
    )
    _write(
        output_dir / "experimental_matrix_table.tex",
        rf"""
\begin{{table}}[H]
\centering
\caption{{Headline ablation matrix over stored decisions. The abstention-only row does not improve risk in this run; the overseer changes the executed-action set and lowers selective risk while imposing deferral cost.}}
\label{{tab:ablation}}
\scriptsize
\begin{{tabularx}}{{\columnwidth}}{{Xrrr}}
\toprule
Policy & Coverage & Error & Avg. reward \\
\midrule
{body}
\bottomrule
\end{{tabularx}}
\end{{table}}
""",
    )


def _failure_count_table(headline: dict[str, Any], output_dir: Path) -> None:
    counts = headline["headline_metrics"]["failure_counts"]
    body = "\n".join(
        rf"\texttt{{{_tex_escape(label)}}} & {count} \\"
        for label, count in sorted(counts.items(), key=lambda item: item[1], reverse=True)
    )
    _write(
        output_dir / "failure_counts_table.tex",
        rf"""
\begin{{table}}[H]
\centering
\caption{{Interpretable failure labels in the headline run. These labels prioritize audit; they do not replace completed human adjudication.}}
\label{{tab:failures}}
\begin{{tabular}}{{lr}}
\toprule
Failure label & Count \\
\midrule
{body}
\bottomrule
\end{{tabular}}
\end{{table}}
""",
    )


def _failure_gallery_table(headline: dict[str, Any], output_dir: Path) -> None:
    rows = headline["failure_gallery"]
    body = "\n".join(
        rf"{_tex_escape(_display_label(row['episode_id']))} & {row['step_index']} & {_tex_escape(row['ticker'])} & {_tex_escape(', '.join(_display_label(label) for label in row['failure_labels']))} & {_tex_escape(row['executed_action'])} to {_tex_escape(row['realized_outcome'])} & {_tex_escape(row['summary'])} \\"
        for row in rows
    )
    _write(
        output_dir / "failure_gallery_table.tex",
        rf"""
\begin{{table*}}[t]
\centering
\caption{{Top-ranked failure-gallery cases. Each row names the episode, failure labels, executed action, realized outcome, and overseer rationale.}}
\label{{tab:failure-gallery}}
\scriptsize
\begin{{tabularx}}{{\textwidth}}{{@{{}}p{{0.12\textwidth}}p{{0.035\textwidth}}p{{0.05\textwidth}}p{{0.19\textwidth}}p{{0.10\textwidth}}X@{{}}}}
\toprule
Episode & Step & Ticker & Labels & Action & Mechanism \\
\midrule
{body}
\bottomrule
\end{{tabularx}}
\end{{table*}}
""",
    )


def _audit_status_table(suite: dict[str, Any], human: dict[str, Any], output_dir: Path) -> None:
    completion = human["completion"]
    rows = [
        ("Publication cells completed", f"{suite['completed_run_count']} / {suite['planned_run_count']}"),
        ("Failed resumable cells", str(len(suite.get("failed_run_ids", [])))),
        ("Not-started cells", str(len(suite.get("missing_run_ids", [])))),
        ("Reviewer A labels complete", f"{completion['expected_count'] - completion['reviewer_a_missing_count']} / {completion['expected_count']}"),
        ("Reviewer B labels complete", f"{completion['expected_count'] - completion['reviewer_b_missing_count']} / {completion['expected_count']}"),
        ("Adjudicated labels complete", f"{completion['expected_count'] - completion['adjudicated_missing_count']} / {completion['expected_count']}"),
        ("Model-vs-human comparison ready", str(human["model_vs_human_ready"])),
    ]
    body = "\n".join(rf"{_tex_escape(name)} & {_tex_escape(value)} \\" for name, value in rows)
    _write(
        output_dir / "audit_status_table.tex",
        rf"""
\begin{{table}}[t]
\centering
\caption{{Current artifact-completion status. Pending cells and missing human labels constrain the empirical claims.}}
\label{{tab:artifact-status}}
\begin{{tabular}}{{ll}}
\toprule
Item & Status \\
\midrule
{body}
\bottomrule
\end{{tabular}}
\end{{table}}
""",
    )


def main() -> None:
    parser = argparse.ArgumentParser(description="Export LaTeX assets for the Safe MarketUniverses submission paper.")
    parser.add_argument("--headline-summary", default="outputs/benchmark/smu_headline_v1/summary.json")
    parser.add_argument("--suite-summary", default="outputs/benchmark/publication_suite_summary.json")
    parser.add_argument("--preliminary-json", default="report/preliminary_results.json")
    parser.add_argument("--human-audit-summary", default="outputs/human_audit/smu_headline_v1/human_audit_summary.json")
    parser.add_argument("--output-dir", default="report/generated")
    args = parser.parse_args()

    output_dir = Path(args.output_dir)
    output_dir.mkdir(parents=True, exist_ok=True)

    headline = _load_json(args.headline_summary)
    suite = _load_json(args.suite_summary)
    preliminary = _load_json(args.preliminary_json)
    human = _load_json(args.human_audit_summary)

    _write_numbers(headline=headline, suite=suite, human=human, output_dir=output_dir)
    _headline_table(headline, output_dir)
    _corruption_table(headline, output_dir)
    _regime_table(headline, output_dir)
    _suite_table(preliminary, output_dir)
    _matrix_table(headline, output_dir)
    _failure_count_table(headline, output_dir)
    _failure_gallery_table(headline, output_dir)
    _audit_status_table(suite, human, output_dir)
    print(f"Exported LaTeX submission assets in {output_dir}")


if __name__ == "__main__":
    main()
